name: ferry_offline_client
version: 0.0.1
homepage: https://ferrygraphql.com/
description: An offline-ready Ferry GraphQL Client
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gql_link: ^0.4.0
  meta: ^1.1.8
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  ferry_exec: ^0.1.4
  ferry_cache: ^0.5.5
  ferry_hive_store: ^0.4.4
  retry: 3.0.1
  ferry: ^0.10.4
  flutter:
    sdk: flutter
dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
  ferry_test_graphql: ^0.1.4
